#!/bin/sh

set -e

case "$(uname)" in
  Linux)
    if [ -r /etc/os-release ]; then
      case "$(. /etc/os-release && echo "$ID")" in
        debian)
          curl -fsSL "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_$(. /etc/os-release && echo "$VERSION_ID")/Release.key" | sudo gpg --dearmor --yes -o /usr/share/keyrings/kubic-libcontainers-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/kubic-libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_$(. /etc/os-release && echo "$VERSION_ID")/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
          sudo apt update -qq
          sudo apt install -qq -y podman buildah skopeo
          ;;
        ubuntu)
          curl -fsSL "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$(. /etc/os-release && echo "$VERSION_ID")/Release.key" | sudo gpg --dearmor --yes -o /usr/share/keyrings/kubic-libcontainers-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/kubic-libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$(. /etc/os-release && echo "$VERSION_ID")/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
          sudo apt update -qq
          sudo apt install -qq -y podman buildah skopeo
          ;;
      esac
    fi

    if dpkg -l cros-guest-tools podman >/dev/null 2>&1; then
      echo "\033[0;34m==>\033[0m \033[1mCaveats\033[0m"
      cat <<'EOF'
To run Podman in Crostini, open Google Chrome, press Ctrl + Alt + T to get the crosh shell, and run:
  vsh termina

  lxc config set penguin security.nesting true
  lxc restart penguin
  lxc exec penguin -- /bin/sh -c "printf '%s\n' '1000:100000:65536' | tee /etc/subuid /etc/subgid"
  lxc exec penguin -- /bin/sed -i -e 's/^driver[[:space:]]*=.*$/driver = "btrfs"/' /etc/containers/storage.conf
  lxc exec penguin -- /bin/rm -rf /var/lib/containers/storage
EOF
    fi
    ;;
esac
