#!/bin/sh

case "$(uname)" in
  Darwin)
    test -z "${HOMEBREW_PREFIX+_}" && test -x /opt/homebrew/bin/brew && eval "$(SHELL=/bin/sh /opt/homebrew/bin/brew shellenv)"
    test -z "${HOMEBREW_PREFIX+_}" && test -x /usr/local/bin/brew && eval "$(SHELL=/bin/sh /usr/local/bin/brew shellenv)"
    ;;
  Linux)
    test -z "${HOMEBREW_PREFIX+_}" && test -x ~/.linuxbrew/bin/brew && eval "$(SHELL=/bin/sh ~/.linuxbrew/bin/brew shellenv)"
    test -z "${HOMEBREW_PREFIX+_}" && test -x /home/linuxbrew/.linuxbrew/bin/brew && eval "$(SHELL=/bin/sh /home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    ;;
esac
