#!/bin/sh

if test -z "${HOMEBREW_PREFIX+_}"; then
  case "$(uname)" in
    Darwin)
      if test -x /opt/homebrew/bin/brew; then
        eval "$(/opt/homebrew/bin/brew shellenv sh 2>/dev/null)"
      elif test -x /usr/local/bin/brew; then
        eval "$(/usr/local/bin/brew shellenv sh 2>/dev/null)"
      fi
      ;;
    Linux)
      if test -x "$HOME/.linuxbrew/bin/brew"; then
        eval "$("$HOME/.linuxbrew/bin/brew" shellenv sh 2>/dev/null)"
      elif text -x /home/linuxbrew/.linuxbrew/bin/brew; then
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv sh 2>/dev/null)"
      fi
      ;;
  esac
fi
