#!/bin/sh

command podman run --rm -it \
  --entrypoint '["/bin/sh", "-c", "export PS1=\"${debian_chroot:+($debian_chroot)}\\u@\\h:\\w\\\\$ \"; test -x /bin/zsh && exec /bin/zsh \"$@\" || test -x /bin/bash && exec /bin/bash \"$@\" || exec /bin/sh \"$@\"", "--"]' \
  --env "debian_chroot=$1" \
  --volume "$HOME/.config/git/attributes:/root/.config/git/attributes:ro" \
  --volume "$HOME/.config/git/config:/root/.config/git/config:ro" \
  --volume "$HOME/.config/git/ignore:/root/.config/git/ignore:ro" \
  --volume "$HOME/.gitconfig:/root/.gitconfig:ro" \
  --volume "$PWD:$PWD" \
  --workdir "$PWD" \
  -- "$@"
