#!/bin/sh

command podman run --rm -it \
  --entrypoint /bin/bash \
  --volume "$HOME/.config:/root/.config:ro" \
  --volume "$HOME/.gitconfig:/root/.gitconfig:ro" \
  --volume "$PWD:/build" \
  --workdir /build \
  "$@"
