#!/bin/sh

set -e

if ! command -v brew >/dev/null 2>&1; then
  if [ "$HOME" = /home/linuxbrew ]; then
    export NONINTERACTIVE=1
  fi
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi
case "$(uname)" in
  Darwin)
    eval "$(SHELL=/bin/sh /usr/local/bin/brew shellenv)"
    ;;
  Linux)
    eval "$(SHELL=/bin/sh ~/.linuxbrew/bin/brew shellenv)"
    ;;
esac

xargs brew install <<'EOF'
  ag
  fd
  fzf
  node
  sqlite
  tmux
  vim
EOF
