#!/bin/zsh

dircolors () {
  local LS_COLORS attribute color background_color modifier background_modifier
  local ATTRIBUTES='dilnsopiexbdcdsusgtwow'
  [ -n "$LSCOLORS" ] || local LSCOLORS='exfxcxdxbxegedabagacad'

  local i
  for i in {0..20..2}; do
    attribute=${ATTRIBUTES:($i):2}

    modifier=$(printf "%d" "'${LSCOLORS:($i):1}")
    if [ "$modifier" -ge 97 ] && [ "$modifier" -le 104 ]; then
      color="$(($modifier - 67))"
    elif [ "$modifier" -ge 65 ] && [ "$modifier" -le 72 ]; then
      color="01;$(($modifier - 35))"
    elif [ "$modifier" -eq 120 ]; then
      color="00"
    fi

    background_modifier=$(printf "%d" "'${LSCOLORS:($i + 1):1}")
    if [ "$background_modifier" -ge 97 ] && [ "$background_modifier" -le 104 ]; then
      background_color=";$(($background_modifier - 57))"
    elif [ "$background_modifier" -ge 65 ] && [ "$background_modifier" -le 72 ]; then
      background_color=";01;$(($background_modifier - 25))"
    fi

    LS_COLORS+="$attribute=$color$background_color:"
  done
  echo "LS_COLORS='$LS_COLORS';"
  echo "export LS_COLORS"
}

dircolors
